# Site settings
title: Dec Norton
email: decnorton@gmail.com
description:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://decnorton.uk" # the base hostname & protocol for your site
twitter_username: decnorton
github_username:  decnorton
timezone: Europe/London

# Permalink
permalink: /:year/:month/:title/

# Build settings
markdown: kramdown
exclude: ['_assets', '_scripts', 'README.md']

# Pagination
paginate: 10
paginate_path: "page/:num/"

excerpt_separator: <!--more-->
